$(function () {

    $('#a:in-viewport').addClass('animated fadeInDown');

    $(window).scroll(function () {
        $('#a:in-viewport(-300)').css('transform', 'translateX(10em)');
    });
    
    animationClick('#beshen-1', '#beshen-1', 'shake')
    animationClick('#beshen-2', '#beshen-2', 'shake')
    animationClick('#beshen-3', '#beshen-3', 'shake')
    animationClick('#beshen-4', '#beshen-4', 'shake')
    animationClick('#beshen-5', '#beshen-5', 'shake')
    animationClick('#beshen-6', '#beshen-6', 'shake')
    animationClick('#beshen-7', '#beshen-7', 'shake')
    animationClick('#beshen-8', '#beshen-8', 'shake')
    animationClick('#beshen-9', '#beshen-9', 'shake')
    animationClick('#beshen-10', '#beshen-10', 'shake')
    animationClick('#beshen-11', '#beshen-11', 'shake')
    animationClick('#beshen-12', '#beshen-12', 'shake')
    animationClick('#beshen-13', '#beshen-13', 'shake')
    animationClick('#beshen-14', '#beshen-14', 'shake')
    animationClick('#beshen-15', '#beshen-15', 'shake')
    animationClick('#beshen-16', '#beshen-16', 'shake')
    
    animationClick('#bomb-1', '#bomb-1', 'tada')
    animationClick('#bomb-2', '#bomb-2', 'tada')
    animationClick('#bomb-3', '#bomb-3', 'tada')
    animationClick('#bomb-4', '#bomb-4', 'tada')
    animationClick('#bomb-5', '#bomb-5', 'tada')
    animationClick('#bomb-6', '#bomb-6', 'tada')
    animationClick('#bomb-7', '#bomb-7', 'tada')
    animationClick('#bomb-8', '#bomb-8', 'tada')
    animationClick('#bomb-9', '#bomb-9', 'tada')
    animationClick('#bomb-10', '#bomb-10', 'tada')
    animationClick('#bomb-11', '#bomb-11', 'tada')
    animationClick('#bomb-12', '#bomb-12', 'tada')
    animationClick('#bomb-13', '#bomb-13', 'tada')
    animationClick('#bomb-14', '#bomb-14', 'tada')
    animationClick('#bomb-15', '#bomb-15', 'tada')
    animationClick('#bomb-16', '#bomb-16', 'tada')
    animationClick('#bomb-17', '#bomb-17', 'tada')
    animationClick('#bomb-18', '#bomb-18', 'tada')
    animationClick('#bomb-19', '#bomb-19', 'tada')
    animationClick('#bomb-20', '#bomb-20', 'tada')
    animationClick('#bomb-21', '#bomb-21', 'tada')
    
    animationClick('#soldier-1', '#soldier-1', 'bounce')
    animationClick('#soldier-2', '#soldier-2', 'bounce')
    animationClick('#soldier-3', '#soldier-3', 'bounce')
    animationClick('#soldier-4', '#soldier-4', 'bounce')
    animationClick('#soldier-5', '#soldier-5', 'bounce')
    animationClick('#soldier-6', '#soldier-6', 'bounce')
    animationClick('#soldier-7', '#soldier-7', 'bounce')
    animationClick('#soldier-8', '#soldier-8', 'bounce')
    animationClick('#soldier-9', '#soldier-9', 'bounce')
    animationClick('#soldier-10', '#soldier-10', 'bounce')
    animationClick('#soldier-11', '#soldier-11', 'bounce')
    
    animationClick('#butterfly-1', '#butterfly-1', 'shake')
    animationClick('#butterfly-2', '#butterfly-2', 'shake')
    animationClick('#butterfly-3', '#butterfly-3', 'shake')
    animationClick('#butterfly-4', '#butterfly-4', 'shake')
    animationClick('#butterfly-5', '#butterfly-5', 'shake')
    animationClick('#butterfly-6', '#butterfly-6', 'shake')
    animationClick('#butterfly-7', '#butterfly-7', 'shake')
    animationClick('#butterfly-8', '#butterfly-8', 'shake')
    animationClick('#butterfly-9', '#butterfly-9', 'shake')
    animationClick('#butterfly-10', '#butterfly-10', 'shake')
    animationClick('#butterfly-11', '#butterfly-11', 'shake')
    animationClick('#butterfly-12', '#butterfly-12', 'shake')
    animationClick('#butterfly-13', '#butterfly-13', 'shake')
    animationClick('#butterfly-14', '#butterfly-14', 'shake')
    animationClick('#butterfly-15', '#butterfly-15', 'shake')
    animationClick('#butterfly-16', '#butterfly-16', 'shake')
    
    animationClick('#jewel-1', '#jewel-1', 'swing')
    animationClick('#jewel-2', '#jewel-2', 'swing')
    animationClick('#jewel-3', '#jewel-3', 'swing')
    animationClick('#jewel-4', '#jewel-4', 'swing')
    animationClick('#jewel-5', '#jewel-5', 'swing')
    animationClick('#jewel-6', '#jewel-6', 'swing')
    animationClick('#jewel-7', '#jewel-7', 'swing')
    animationClick('#jewel-8', '#jewel-8', 'swing')
    animationClick('#jewel-9', '#jewel-9', 'swing')
    animationClick('#jewel-10', '#jewel-10', 'swing')
    animationClick('#jewel-11', '#jewel-11', 'swing')
    animationClick('#jewel-12', '#jewel-12', 'swing')
    animationClick('#jewel-13', '#jewel-13', 'swing')
    animationClick('#jewel-14', '#jewel-14', 'swing')
    animationClick('#jewel-15', '#jewel-15', 'swing')
    animationClick('#jewel-16', '#jewel-16', 'swing')
    animationClick('#jewel-17', '#jewel-17', 'swing')
    animationClick('#jewel-18', '#jewel-18', 'swing')
    animationClick('#jewel-19', '#jewel-19', 'swing')
    animationClick('#jewel-20', '#jewel-20', 'swing')
    animationClick('#jewel-21', '#jewel-21', 'swing')
    animationClick('#jewel-22', '#jewel-22', 'swing')
    animationClick('#jewel-23', '#jewel-23', 'swing')
    animationClick('#jewel-24', '#jewel-24', 'swing')
    animationClick('#jewel-25', '#jewel-25', 'swing')
    animationClick('#jewel-26', '#jewel-26', 'swing')
    animationClick('#jewel-27', '#jewel-27', 'swing')
    animationClick('#jewel-28', '#jewel-28', 'swing')
    animationClick('#jewel-29', '#jewel-29', 'swing')
    animationClick('#jewel-30', '#jewel-30', 'swing')
    animationClick('#jewel-31', '#jewel-31', 'swing')
    animationClick('#jewel-32', '#jewel-32', 'swing')
    animationClick('#jewel-33', '#jewel-33', 'swing')
    animationClick('#jewel-34', '#jewel-34', 'swing')
    animationClick('#jewel-35', '#jewel-35', 'swing')
    animationClick('#jewel-36', '#jewel-36', 'swing')
    animationClick('#jewel-37', '#jewel-37', 'swing')
    animationClick('#jewel-38', '#jewel-38', 'swing')
    animationClick('#jewel-39', '#jewel-39', 'swing')
    animationClick('#jewel-40', '#jewel-40', 'swing')
    animationClick('#jewel-41', '#jewel-41', 'swing')
    animationClick('#jewel-42', '#jewel-42', 'swing')
    animationClick('#jewel-43', '#jewel-43', 'swing')
    animationClick('#jewel-44', '#jewel-44', 'swing')
    animationClick('#jewel-45', '#jewel-45', 'swing')
    animationClick('#jewel-46', '#jewel-46', 'swing')
    animationClick('#jewel-47', '#jewel-47', 'swing')
    animationClick('#jewel-48', '#jewel-48', 'swing')
    animationClick('#jewel-49', '#jewel-49', 'swing')
    animationClick('#jewel-50', '#jewel-50', 'swing')
    animationClick('#jewel-51', '#jewel-51', 'swing')
    animationClick('#jewel-52', '#jewel-52', 'swing')
    animationClick('#jewel-53', '#jewel-53', 'swing')
    animationClick('#jewel-54', '#jewel-54', 'swing')
    animationClick('#jewel-55', '#jewel-55', 'swing')
    
    animationClick('#man', '#man', 'bounce')

    $(document).on('click', '#a',
        function () {
            $(this).toggleClass("b");
        });
});